
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: plytoteka
    ports:
      - "3010:80"
    depends_on:
      - backend

#Aby dane bazy nie były usuwane po "docker compose down"
volumes:
  db_data:
